Clone Coding/pinterest/pragmatic/accountapp/urls.py
from django.urls import path

from accountapp.views import hello_world,AccountCreateView,AccountDetailView,AccountUpdateView,AccountDeleteView
from django.contrib.auth.views import LoginView, LogoutView

app_name = "accountapp"

urlpatterns = [
    path('hello_world/', hello_world, name='hello_world'),

    path('login/', LoginView.as_view(template_name='accountapp/login.html'), name='login'),
    path('logout/', LogoutView.as_view(), name='logout'),

    path('create/', AccountCreateView.as_view(), name='create'),
    path('detail/<int:pk>', AccountDetailView.as_view(), name='detail'),
    path('update/<int:pk>', AccountUpdateView.as_view(), name='update'),
    path('delete/<int:pk>', AccountDeleteView.as_view(), name='delete'),

]

Clone Coding/pinterest/pragmatic/articleapp/urls.py
from django.urls import path
from django.views.generic import TemplateView

from articleapp.views import ArticleCreateView, ArticleDetailView, ArticleUpdateView, ArticleDeleteView, ArticleListView

app_name = 'articleapp'

urlpatterns = [
    path('list/', ArticleListView.as_view(), name='list'),
    path('create/', ArticleCreateView.as_view(), name='create'),
    path('detail/<int:pk>', ArticleDetailView.as_view(), name='detail'),
    path('update/<int:pk>', ArticleUpdateView.as_view(), name='update'),
    path('delete/<int:pk>', ArticleDeleteView.as_view(), name='delete'),
]

Clone Coding/pinterest/pragmatic/pragmatic/urls.py
from django.conf import settings
from django.contrib import admin
from django.conf.urls.static import static
from django.urls import path,include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('accounts/', include('accountapp.urls')),
    path('profiles/', include('profileapp.urls')),
    path('articles/', include('articleapp.urls')),
    path('comments/', include('commentapp.urls')),
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

Clone Coding/pinterest/pragmatic/templates/base.html
<!DOCTYPE html>
<html lang="ko">

{% include 'head.html' %}

<body style="font-family: 'NanumSquare_acB';">

    {% include 'header.html' %}
    <hr>
    {% block content %}
    {% endblock %}
    <hr>
    {% include 'footer.html' %}

</body>
</html>

Clone Coding/pinterest/pragmatic/templates/footer.html
<div class="pragmatic_footer">
    <div class="pragmatic_footer_button">
        <span>공지사항</span> |
        <span>제휴문의</span> |
        <span>서비스 소개</span>
    </div>
    <div style="margin-top: 1rem;">
        <h6 class="pragmatic_logo">Pragmatic</h6>
    </div>
</div>

Clone Coding/pinterest/pragmatic/templates/head.html
{% load static %}

<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-with, inital-scale=1, shrink-to-fit=no">
    <title>pragmatic</title>
    <!-- BOOTSTRAP LINK -->
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.1.3/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-1BmE4kWBq78iYhFldvKuhfTAU6auU8tT94WrHftjDbrCEXSU1oBoqyl2QvZ6jIW3" crossorigin="anonymous">

<!--GOOGLE FONTS LINK    -->
    <link rel="preconnect" href="https://fonts.googleapis.com">
    <link rel="preconnect" href="https://fonts.gstatic.com" crossorigin>
    <link href="https://fonts.googleapis.com/css2?family=Lobster&display=swap" rel="stylesheet">

<!--DEFAULT CSS LINK-->
    <link rel="stylesheet" type="text/css" href="{% static 'base.css' %}">

    <style>
        @font-face {
            font-family: 'NanumSquare_acB';
            src: local('NanumSquare_acB'),
            url("{% static 'fonts/NanumSquare_acB.ttf' %}") format('opentype');
        }

        @font-face {
            font-family: 'NanumSquare_acR';
            src: local('NanumSquare_acR'),
            url("{% static 'fonts/NanumSquare_acR.ttf' %}") format('opentype');
        }

       @font-face {
            font-family: 'NanumSquare_acL';
            src: local('NanumSquare_acL'),
            url("{% static 'fonts/NanumSquare_acL.ttf' %}") format('opentype');
        }

    </style>
</head>

Clone Coding/pinterest/pragmatic/templates/header.html
<div class="pragmatic_header">
    <div>
        <h1 class="pragmatic_logo">Pragmatic</h1>
    </div>
    <div>
        <a href="{% url 'articleapp:list' %}">
            <span>Articles</span>
        </a>

        <span>nav2</span>
        <span>nav3</span>
        
        {% if not user.is_authenticated %}
        <a href="{% url 'accountapp:login' %}?next={{ request.path }}">
            <span>login</span>
        </a>
        <a href="{% url 'accountapp:create' %}">
            <span>SignUp</span>
        </a>
        {% else %}
        <a href="{% url 'accountapp:detail' pk=user.pk %} ">
            <span>MyPage</span>
        </a>
        <a href="{% url 'accountapp:logout' %}?next={{ request.path }}">
            <span>logout</span>
        </a>
        {% endif %}
    </div>
</div>